export { ReactComponent as PlaneIcon } from "./plane.svg";
export { ReactComponent as DoubleCheckIcon } from "./double-check.svg";
export { ReactComponent as CheckIcon } from "./check.svg";
export { ReactComponent as PhoneIcon } from "./phone.svg";
export { ReactComponent as MessageIcon } from "./message.svg";
export { ReactComponent as KebabMenuIcon } from "./kebab-menu.svg";
export { ReactComponent as LayoutIcon } from "./layout.svg";
export { ReactComponent as BackArrowIcon } from "./back-arrow.svg";
export { ReactComponent as HamburgerIcon } from "./hamburger.svg";
